## Introduction to Python
---  
### Table of Contents
  - Getting Started (Hello World)
  - [Variables](#Variables)
  - [Data Structures](#Data-Structures)
    - [sequence data](#Sequence-Data-(lists-and-strings))
      - indexing, slicing, and stride
      - other list and string methods
    - [data dictionaries](#Data-Dictionaries)
  - [Operators](#Operators)
    - [arithmetic operators](#Arithmetic-Operators)
    - [conditional operators](#Comparison-Operators)
    - [logical operators](#Logical-Operators) and short circuit evaluation
  - [Control Flow](#Control-Flow)
    - [if, elif, else](#if,-elif,-else)
    - [for loops](#For-Loops)
  - [Functions, Standard Libraries, and Packages and Modules](#Functions,-Standard-Libraries,-and-Packages-and-Modules)

---  
### Getting Started
The first thing to do is of course to print "Hello World". (This is not just customary, we also do this to make sure that everything is set up and working correctly). Type the code that you see below into your Python editor (and continue doing so for all the examples):


In [345]:
print('Hello World') # You can use single or double quotations (but try to be consistent)

Hello World


---  
### Variables  
#### Overview
A variable consists of a variable name (identifier) and a storage location that can store a value that can be referenced using the variable name.  When using variables in Python:
 - There is no need to declare the variables. Simply type:  
 variable_name = constant
 - Variable names
    - Are case sensitive (use lower case letters and underscores to connect multiple words)
    - Can only contain alpha-numeric characters (and underscores)
    - Cannot start with numbers
    - Variable names that are easy to understand.
 - Data types
    - Variables can store integers, float, Boolean, and strings (a specific variable can change type after it has first been set)
    - To find out the data type of the value in a variables use type(variable_name)
    - Converting/casting data types using int(), float(), and str(), e.g., int(variable_name).  The table below provides more information about these functions. When casting, the actual data type of the variable is not changed (the casting is not done in-place, i.e., a copy is returned and the original variable is left unmodified).


Function | Returns   
:------|------|
   int()  | an integer from a float (by rounding down to the previous whole number) or a string (if the string represents a whole number)
   float()  | a float from an integer or a string (if the string represents a float or an integer)
   str()  | a string from a wide variety of data types, including integers and floats
  

#### Exercises
_Exercise 1.1_  
Create a new variable named sales and assign the value 57000 to this variable.

In [346]:
sales = 57000
print(sales)                # I am also printing to see the results of my code

57000


_Exercise 1.2_  
Variable names are case sensitive. Try printing Sales (notice that sales was not capitalized earlier) 

In [336]:
print(Sales)                # This code returns an error because Sales is not defined - we earlier defined sales but not Sales (Python is case sensitive) 

NameError: name 'Sales' is not defined

_Exercise 1.3_  
a. Create a variable named sales@2012 and set this variable to equal sales.

In [337]:
sales@2012 = sales       # This code returns an error because variable names can only contain alpha-numerics and underscores

SyntaxError: can't assign to operator (<ipython-input-337-cdfa30e40ed5>, line 1)

  b. Create a variable named 2012sales and set this variable to equal sales.

In [338]:
2012sales = sales      # This code returns an error because variable names cannot start with numbers 

SyntaxError: invalid syntax (<ipython-input-338-fbf08edb1d23>, line 1)

_Exercise 1.4_  
Create three new variables, expenses, clean_audit_opinion, and company_name and assign the values 57.68 (a float), True (a Boolean), and 'ACME' (a string), respectively, to these variables.  Use type(variable_name) to print the data type of each variable.

In [339]:
expenses = 57.68
clean_audit_opinion = True
company_name = 'ACME'
print(type(expenses))
print(type(clean_audit_opinion))
print(type(company_name))

<class 'float'>
<class 'bool'>
<class 'str'>


_Exercise 1.5_  
Convert expenses (float) to an integer.

In [340]:
print(expenses)
print(int(expenses))
print(expenses)          # The int function returns the expenses value converted to an integer, but the casting is not done in-place.
print(type(expenses))
print(type(int(expenses)))

expenses = int(expenses) # To change the actual data type of the variable, the converted data has to be assigned to the variable
print(expenses)   
print(type(expenses))

57.68
57
57.68
<class 'float'>
<class 'int'>
57
<class 'int'>


---

### Data Structures
#### Overview  
Data structures (e.g., sequences and dictionaries) store multiple values. Python has a number of data structures, including sequence data such as lists and strings, and dictionaries:
 - Sequence Data - lists and strings are both sequence data types (the order of the data matters) where the initial elements is assigned the index 0 (i.e., sequences are zero-based numbered), the second element then has index 1, and so on. Negative index is used to index starting from the last element of the sequence, e.g., -1 refers to the last index, -2 refers to the second last index, and so on (see the examples section below for a picture of this).
   - __Strings__ store characters and are immutable (they are not designed to be extended or reduced). Each string is enclose by quotation marks, e.g.,:  
   *company_name = 'ACME'*. 
   - __Lists__ can contain a mix of different data types and are mutable.  The elements in lists are separated by commas and the list of elements is enclosed by square brackets, e.g.,: 
   *list_name = [57.68, True, 'ACME']*.
   - (There is also a data structure called a tuple that can contain any type of object like a list but is immutable list a string; tuple data structures are generally used for heterogeneous (different) datatypes and list for homogeneous (similar) datatypes. Since tuple are immutable, iterating through tuple is faster than with list. So there is a slight performance boost.  The elements in tuples are separated by commas and the tuple is enclose by parentheses, e.g., (57.68, True, 'ACME'). We focus on lists (and strings) because they use square brackets and behave similarly to numpy arrays and pandas dataframes, which is what we will be using almost exclusively later).  
   - Lists and strings share a number of methods, including methods for extracting specific elements).  The examples below focus on lists, but the concepts also apply to strings.
 - A __dictionary__ is a sequence of items that is not sorted. Dictionaries are not sorted. Each item is a pair made of a key and a value (think attribute name and attribute value) separated by colons. Items are separated by commas and the list of items is enclosed in curly brackets, e.g.,:  
 *dictionary_name = {'Expenses': 57.68, 'Audit Opinion' : True, 'Company Name' : 'ACME']*.

#### Sequence Data (lists and strings)
This section will first focus on how to extract elements from lists. We will later also learn some additional functions, including how to add and delete elements and locate specific elements in sequences.  The table below provides a summary of some of the most important sequence functions (after creating the initial list, the examples below go through these functions in the order they are listed in the table).

|     Method/Operation       	|     Result |
|---| --- |
|    s[i]                    	|    ith item of s, origin 0                                                                                                        	|
|    s[i:j]                  	|    slice of s from i to j                                                                                                         	|
|    s[i:j:k]                	|    slice of s from i to j with   step k                                                                                           	|
|    s + t                   	|    the concatenation   of s and t                                                                                                 	|
|    s.remove(x)             	|    remove from s the first element with value x                                                                                   	|
|    del s[i:j]              	|    delete from s slice of s from i to j                                                                                           	|
|    x in s                  	|    True if an item of s is equal to x, else False                                                                                 	|
|    s.index(x, i, j)       	|    index of the first occurrence of x in s (at or after index i and before index j; i and j are optional)                         	|
|    len(s)                  	|    length of s                                                                                                                    	|
|    min(s)                  	|    smallest item of s                                                                                                             	|
|    max(s)                  	|    largest item of s                                                                                                              	|
|    s.count(x)              	|    total number of occurrences of x in s                                                                                          	|

__Creating Lists__  
__Exercise 2.1__  
Create a list that contains five elements: 10, 100, 1000, 10000, and 'large' and name this list 'list_example'.

In [299]:
list_example = [10, 100, 1000, 10000, 'large']


__Extracting Single Elements (indexing)__  
In the list we just created, the different elements have the indexes as shown below.  These indexes can be used to extract a single elements from the list.  For example, to get 1000, you can use 2 and type list_example[2] (using -3, i.e., list_example[-3], returns the same result).
 
. | 10 | 100 | 1000 | 10000 | large | .
:------:|:------:|:------:|:------:|:------:|:------:|:------:
. | 0 | 1 | 2 | 3 | 4 | 5 | 6
-6 | -5 | -4 | -3 | -2 | -1 | .

__Exercise 2.2__  
a. Extract the value 'large' using a positive number.   
b. Extract the value 100 using a negative number.  
c. Create a string named city_name and assign the value 'San Diego' to this string.  Then (i) extract D using a positive number and (ii) extract e using a negative number.  

In [300]:
print(list_example[4])
print(list_example[-4])

city_name = 'San Diego'
print(city_name[4])
print(city_name[-3])

large
100
D
e


**Extracting Multiple Elements (slicing)**  
You can extract a sequence out of a list by specifying the start and end index, i.e., list_example[n:m]. The slice will include elements between index n (including this element) and index m (excluding this element).  For example to get [100, 1000], you can use either [1:3] or [-4:-2]:

In [301]:
print(list_example[1:3])
print(list_example[-4:-2])

[100, 1000]
[100, 1000]


If you leave the first value empty then 0 is assumed.  If you leave the second value empty then the index of the last element + 1 is assumed (in list_example the last element has index 5).  Using [:3] will extract [10, 100, 1000] and [3:] will extract [10000, large]:

In [302]:
print(list_example[:3])
print(list_example[3:])

[10, 100, 1000]
[10000, 'large']


__Exercise 2.3__  
a. Extract [10, 100, 1000] using a negative number end value (and empty start)  
b. Extract [10000, 'large'] using a negative number start value (and empty end value)  
c. Extract 'San' from city_name using positive numbers (and empty start or end values as appropriate)  
d. Extract 'Diego' from city_name using negative numbers (and empty start or end values as appropriate)  

In [303]:
print('a: ' + str(list_example[:-2]))            # In addition to printing, I have added the following code 'a: ' + str(solution) to make it easier to read the results.
print('b: ' + str(list_example[-2:]))
print('c: ' + str(city_name[:3]))
print('d: ' + str(city_name[-5:]))

a: [10, 100, 1000]
b: [10000, 'large']
c: San
d: Diego


__Using Stride__  
String slicing can accept a third parameter, the stride, which specifies how many elements to move forward when traversing the sequence when selecting the next element.  When stride is omitted, the stride parameter defaults to 1, which means that each element between the two index numbers is extracted.  A stride of 2 extracts every other element (starting with the first element), a stride of 3 extracts every third element, etc.  

__Exercise 2.4__  
Select every other element in the list_example sequence

In [304]:
print(list_example[::2])

[10, 1000, 'large']


__Exercise 2.5__  
Select every other element starting with the second element in the list_example sequence

In [305]:
print(list_example[1::2])

[100, 10000]


It is also possible to select elements starting from the right, i.e., we traverse the sequence from right to left, by using negative stride values, i.e., list_example[n:m:-k].  The start and end index are still defined by n and m, respectively.  However, since we are traversing from right to left n now has to be to the right of m, i.e., n>m.  When n is empty the start position is now all the way to the right.  When m is empty the end position is all the way to the left.  

__Exercise 2.6__  
a. Use negative stride and create a new list that reverses the order of the original list.  Name this list reverse_list_example. See note below related to reversing lists.  
b. Instead of creating a new list, simply print the original list in reversed order but now exclude the last value (i.e., 'large' should not be included).  Use positive or empty values for the start and end values as appropriate.  
c. Create the same results as in 5.b but use a negative values for the start value.
d. Extract 10000, 100.

*Note:* There are three different approaches related to reversing lists: (i) slicing using negative stride, (ii) using a method called reverse, e.g., list_example.reverse, and (iii) using a function call reversed, e.g., reversed(list_example). When slicing, we create a new list that is the reverse of the original list.  When using reverse we reverse the list in-place (we directly modify the original list).  When using reversed we create an iterator object. We can of course create additional code that further modify the output and makes the outcomes equivalent, but the performance is generally best if the approach is selected based on the desired output. As an extra exercise try using this two alternatives to create a reversed list.  Note that you need to use list(iterator) to create a list from an iterator.

In [306]:
reverse_list_example = list_example[::-1]    #Start all the way to the right, select each element going backwards, and stop all the way to the left
print(reverse_list_example)
print(list_example[3::-1])                   #Start at 3, select each element going backwards, and stop all the way to the left.
print(list_example[-2::-1])                  #Start at -2, select each element going backwards, and stop all the way to the left.
print(list_example[3::-2]) 

['large', 10000, 1000, 100, 10]
[10000, 1000, 100, 10]
[10000, 1000, 100, 10]
[10000, 100]


__Adding Elements__  
To add elements contained two lists, s and t, we can use the concatenation operator +, i.e., s + t, to create a new list u.  If s = [1, 10] and t=[45, 22, 50] then if we set u = s + t then u will be [1, 10, 45, 22, 50].  To instead add t to s (and update s inplace), we can say s += t, (which is similar to s = s + t, except that the latter still creates a new variable). There are also two specific methods that can be used to achieve the same result: append to add a single element and extend to add multiple elements (a list) to an existing list.  When using s += t, Python actually runs the extend method, so s += t is equivalent to s.extend(t).  
  
__Exercise 2.7__  
a. Add 'very_large' to list_example using append  
b. Add [101, 102] as a single element to list_example using append  
c. Add ['even_larger', 'the largest'] as two separate elements to list_example using extend  
d. Add [1, 2, 3, 4] as four separate elements to list_example using the concatenation operator  
e. Add [1, 2, 3, 4] as a single element to list_example using the concatenation operator

In [307]:
list_example.append('very_large')
print(list_example)

list_example.append([101, 102])
print(list_example)

list_example.extend(['even_larger', 'the largest'])
print(list_example)

list_example += [1, 2, 3, 4]
print(list_example)

list_example += [[101, 102]]
print(list_example)


[10, 100, 1000, 10000, 'large', 'very_large']
[10, 100, 1000, 10000, 'large', 'very_large', [101, 102]]
[10, 100, 1000, 10000, 'large', 'very_large', [101, 102], 'even_larger', 'the largest']
[10, 100, 1000, 10000, 'large', 'very_large', [101, 102], 'even_larger', 'the largest', 1, 2, 3, 4]
[10, 100, 1000, 10000, 'large', 'very_large', [101, 102], 'even_larger', 'the largest', 1, 2, 3, 4, [101, 102]]


__Removing Elements__  
To remove elements, remove('element_value') is used to remove an element with a specific value (but only the first occurrence of the element) and del list[n:m] is used to remove elements based on their index.  Both remove and del operate inplace.  
  
__Exercise 2.8__  
a. Remove the value 'even_larger'  
b. Remove the first element that contain the value [101, 102]  
c. Remove the element with index 2, i.e., 1000  
d. Remove the second to last element and the three elements prior to this element in the sequence, i.e., remove [1, 2, 3, 4]


In [308]:
print(list_example)

list_example.remove('even_larger') 
print(list_example)

list_example.remove([101,102]) 
print(list_example)

del list_example[2]
print(list_example)

del list_example[-5:-1]
print(list_example)

[10, 100, 1000, 10000, 'large', 'very_large', [101, 102], 'even_larger', 'the largest', 1, 2, 3, 4, [101, 102]]
[10, 100, 1000, 10000, 'large', 'very_large', [101, 102], 'the largest', 1, 2, 3, 4, [101, 102]]
[10, 100, 1000, 10000, 'large', 'very_large', 'the largest', 1, 2, 3, 4, [101, 102]]
[10, 100, 10000, 'large', 'very_large', 'the largest', 1, 2, 3, 4, [101, 102]]
[10, 100, 10000, 'large', 'very_large', 'the largest', [101, 102]]


__Finding Elements__  
The in operator can be used to examine whether a value is part of a sequence, e.g., x in s returns True if an item in list s is equal to x (you can also use x not in s to instead return True if there are no items in s that are equal to x). The function s.index(x) instead returns the index (the location) of the first occurrence of x in s.  The index function can also take two additional optional arguments, i and j, that indicate between which indexes in s should be examined for x (at or after index i and before index j).
  
__Exercise 2.9__  
a. Determine if [101, 102] is part of list_example  
b. Determine if 'even_larger' is part of list_example  
c. Determine the index of [101, 102] in list_example  
d. Determine the index of 'very large' in list_example  
e. Determine the index of 100 in list_example  
f. Add the value 10000 to list_example and then determine the index of the second 10000  
g. Determine the index of the space (' ') in city_name  
h. Extract all the characters after the space in city_name (exclude the space), recall that the string city_name contains 'San Diego'  
i. Extract all the characters before the space in city_name

In [309]:
print(list_example)
print('a: ' + str([101,102] in list_example))
print('b: ' + str('even_larger' in list_example))

print('c: ' + str(list_example.index([101,102])))
print('d: ' + str(list_example.index('very_large')))
print('e: ' + str(list_example.index(100)))

list_example = list_example + [10000]
print('f: ' + str(list_example.index(10000,list_example.index(10000)+1)))

print('g: ' + str(city_name.index(' ')))
print('h: ' + str(city_name[city_name.index(' ')+1:]))
print('i: ' + str(city_name[:city_name.index(' ')]))

[10, 100, 10000, 'large', 'very_large', 'the largest', [101, 102]]
a: True
b: False
c: 6
d: 4
e: 1
f: 7
g: 3
h: Diego
i: San


**Aggregate Functions**  
While not exactly  aggregate functions, functions like min, max, and count are common aggregate functions.  The min(s) and max(s) functions returns that smallest and largest values in the sequence s (note that all elements have to be numeric, i.e., data ).  The len(s) function returns the number of items in the sequence s.  The method s.count(x) is similar to len(s) in that it also returns a count, but instead of returning the total number of items in the sequence s, s.count(x) returns the number of occurrences of x in s.  
  
__Exercise 2.10__  
a. Find the largest number among all numeric values in list_example (you can simply take slices of all numeric values from list_example)  
b. Find the smaller number among all number values in list example  
c. Count how many items there are in total in list_example   
d. Count how many items have the value 10000 in list_example  

In [310]:
print(list_example)
print(max(list_example[0:3]+list_example[-1:]))          # Combine slices that contain numeric values
print(min(list_example[0:3]+list_example[-1:]))
print(len(list_example))
print(list_example.count(10000))

[10, 100, 10000, 'large', 'very_large', 'the largest', [101, 102], 10000]
10000
10
8
2


In [311]:
#print(list_example.index([101,102]))
#print(len(list_example)-1-list_example[::-1].index([101,102])) # not the fastest way to do this, but easy and clean 
                                      
#import timeit
#print(timeit.timeit('len(l_e)-1-l_e[::-1].index(833)', 'l_e = list(range(1000))', number=1000))
#print(timeit.timeit('list(reversed(le)).index(833)', 'le = list(range(1000))', number=1000))
#_list.reverse() modifies the list itself - it reverses the elements of the list in place., whereas reversed(_list) returns an iterator ready to traverse the list in reversed order. 


__Additional String Methods__  
The sequence type string have some additional functions that only work for strings.  I have listed some of the more important string functions below. While this tutorial does not go through them, I expect that you are able to use them when needed:  

|Method/Operation|Result|
|:-------|:-------|
|    str.capitalize()                      	|    Returns a copy of str with the first character capitalized and the rest lowercased.|
|    str.upper()                          	|    Returns a copy of str with all cased characters capitalized.|
|    str.lower()                           	|    Return a copy of str all cased characters lowercased.|
|    str.find(x, i, j)                  	|    Similar to s.index(x, i, j) except that find returns -1 rather than ValueError if x is not found in the sequence.  Also note that when index is used with lists, x has to be a single item, but in find (and index when used with a string) x can be a substring (e.g., contain multiple items).|
|    str.rfind(x, i, j)                 	|    Return the highest index of items in str that have the value x.|
|    str.strip([chars])                    	|    Returns a copy of str with leading and trailing whitespaces removed.  Can alternatively remove leading and trailing characters that are specified in the chars argument removed. The chars argument is a string that specifies characters to remove (all combinations of the characters are removed), e.g., for city_name.strip('aoS') will return 'n Dieg'.  Two related functions, str.lstrip() and str.rstrip strips only leading and trailing characters, respectively.|

#### Data Dictionaries  
Data dictionaries can store mixed types of data, but the elements are unordered.  Instead each element is a key-value pair, i.e., key: value. The elements are separated by commas and the entire dictionary is enclosed by curly brackets, e.g., dict_1 = {key_1: value_1, key_2: value_2}.  In addition to storing single values, key-value pairs can also store lists, e.g, dict_lists_1 = {key_1: [value_1_1, value_1_2], key_2: [value_2_1, value_2_2]}.  
  
__Creating Data Dictionaries__  
__Exercise 2.11__  
a. Create a dictionary named acme_financials with three key-value pairs: expenses-132, sales-164, and number_of_customers-1023.   
b. Create a dictionary named acme_multiple_financials with three key-value pairs each containing a list of values: expenses-29, 32, 34, 37, sales-38, 44, 42, 40, and number_of_customers-250, 261, 254, 258.  

In [312]:
acme_financials = {'expenses': 132, 'sales': 164, 'number_of_customers': 1023}
print('a: ' + str(acme_financials))
acme_multiple_financials = {'expenses': [29, 32, 34, 37], 'sales': [38, 44, 36, 40], 'number_of_customers': [250, 261, 254, 258]}
print('b: ' + str(acme_multiple_financials))

a: {'expenses': 132, 'sales': 164, 'number_of_customers': 1023}
b: {'expenses': [29, 32, 34, 37], 'sales': [38, 44, 36, 40], 'number_of_customers': [250, 261, 254, 258]}


__Extracting Elements__  
Because elements are unordered, values are accessed by keys instead of indexes, e.g., dict_1['key_1'] returns value_1.
  
__Exercise 2.12__  
a. Extract sales out of acme_financials  
b. Extract sales out of acme_multiple_financials  
c. Extract the second sales value out of acme_multiple_financials, i.e., 44.

In [313]:
print('a: ' + str(acme_financials['sales']))
print('b: ' + str(acme_multiple_financials['sales']))
print('c: ' + str(acme_multiple_financials['sales'][1]))

a: 164
b: [38, 44, 36, 40]
c: 44


__Adding and Deleting Elements__  
The code to add a single element to an existing dictionary follows the structure: dict_1['new_key']=value_1.  The dict.update method is used to add multiple elements, e.g., dict_1.update({'new_key_1'=value_1, 'new_key_2'=value_2, etc.}).  To delete an element, del is used, e.g., del dict_1[key_to_delete_1], dict_1[key_to_delete_2], etc. 
  
__Exercise 2.13__  
a. Add a new key-value pair with the key 'assets' and the values 378, 379, 376, 390 to acme_multiple_financials.  
b. Add two new key-value pairs with the keys 'AR' and 'AP' and values 38, 37, 36, 39, and 78, 39, 76, 90, respectively, to acme_multiple_financials.  
c. Delete the key-value pair with the key 'assets' from acme_multiple_financials.

In [314]:
acme_multiple_financials['assets'] = [378, 379, 366, 390]
print('a: ' + str(acme_multiple_financials))

acme_multiple_financials.update({'AR':[38, 37, 36, 39], 'AP':[78, 39, 76, 90]})
print('b: ' + str(acme_multiple_financials))

del acme_multiple_financials['assets']
print('c: ' + str(acme_multiple_financials))

a: {'expenses': [29, 32, 34, 37], 'sales': [38, 44, 36, 40], 'number_of_customers': [250, 261, 254, 258], 'assets': [378, 379, 366, 390]}
b: {'expenses': [29, 32, 34, 37], 'sales': [38, 44, 36, 40], 'number_of_customers': [250, 261, 254, 258], 'assets': [378, 379, 366, 390], 'AR': [38, 37, 36, 39], 'AP': [78, 39, 76, 90]}
c: {'expenses': [29, 32, 34, 37], 'sales': [38, 44, 36, 40], 'number_of_customers': [250, 261, 254, 258], 'AR': [38, 37, 36, 39], 'AP': [78, 39, 76, 90]}


---  
### Operators

#### Arithmetic Operators
|     Operator     	|      Example      	|       Meaning       	|
|:----------------:	|:-----------------:	|:----------------------------------------	|
|         +        	|       a + b       	|    Addition               	|
|         -        	|       a - b       	|    Subtraction                       	|
|         *        	|    a * b    	|    Multiplication    	|
|         /        	|       a / b       	|    Division                              	|
|         %        	|       a % b       	|    Modulo (reminder)                     	|
|        **        	|       a ** b      	|    Exponentiation                        	|

__Exercise 3.1__  
a. Print total expenses by summing the four expense values in acme_multiple_financials  
b. Print sales minus expenses based on the first element in each sequence  
c. Calculate sales per employee based on the first value in each sequence

In [315]:
print(acme_multiple_financials['sales'][0] + acme_multiple_financials['sales'][1]
      + acme_multiple_financials['sales'][2] + acme_multiple_financials['sales'][3])       # We will later learn how to create a loop to automate this
print(acme_multiple_financials['sales'][0]-acme_multiple_financials['expenses'][0])        # We will later use NumPy (and Pandas) to add each element of an array to each element of a second array
print(acme_multiple_financials['sales'][0]/acme_multiple_financials['number_of_customers'][0])

158
9
0.152


The arithmetic operators can also be used in-place when an operation is done to a variable that is also on the left-hand side of the equal sign.  For example if c = 3 and we want to add 5 to c then we can write c = c + 5 or c += 5.  

#### Comparison Operators  
Conditional/comparison operators return True or False.  

|    Operator    	|    Example    	|                                   Result                                   	|
|:--------------:	|:-------------:	|:--------------------------------------------------------------------------	|
|       ==       	|     a == b    	|    True if the value of a is **equal to** the value of b; otherwise False    	|
|       !=       	|     a != b    	|    True if a is **not equal to** b; otherwise False                          	|
|       <        	|     a < b     	|    True if a is **less than** b;   otherwise False                             	|
|       <=       	|     a <= b    	|    True if a is **less than or equal to** b; otherwise False                 	|
|       >        	|     a > b     	|    True if a is **greater than** b; otherwise False                          	|
|       >=        	|     a >= b     	|    True if a is **greater than or equal to** b; otherwise False                          	|

__Exercises 3.2__  
a. Evaluate if sales is more than expenses using the first element in each sequence.  
b. Evaluate if sales is less than expenses using the first element in each sequence.  
c. Evaluate if sales is equal to expenses using the first element in each sequence.  
d. Evaluate if sales is not equal to expenses using the first element in each sequence.  

In [316]:
print(acme_multiple_financials['sales'][0]>acme_multiple_financials['expenses'][0])
print(acme_multiple_financials['sales'][0]<acme_multiple_financials['expenses'][0])
print(acme_multiple_financials['sales'][0]==acme_multiple_financials['expenses'][0])
print(acme_multiple_financials['sales'][0]!=acme_multiple_financials['expenses'][0])

True
False
False
True


In addition to using comparison operators, all the following are considered false when evaluated in a boolean context (see example below):
- The Boolean value False
- Any value that is numerically zero (e.g., 0, 0.0)
- An empty string
- The special value denoted by the Python keyword None  

Virtually any other object built into Python is regarded as true.

In [317]:
print(bool(False), bool(0), bool(''), bool(-1), bool('Hello'), bool(None))

False False False True True False


#### Logical Operators  
The logical operators and, not, and or modify and join together expressions evaluated in a boolean context to create more complex conditions.  
  
  |    Operator    	|    Example    	|                                      Meaning                                      	|
|:--------------:	|:-------------:	|:---------------------------------------------------------------------------------	|
|       not      	|     not x     	|    True if x is False,   False if x is True (reverses the boolean value of x)     	|
|       or       	|     x or y    	|    True if   either x or y is True; otherwise False                               	|
|        ^       	|    x xor y    	|    True if one and   only one of the inputs (x and y) is true; otherwise False    	|
|       and      	|    x and y    	|    True if   both x and y are True; otherwise False                               	|

**Exercises 3.3**  
a. Perform the same comparison as in 3.2.d, but instead of using "!=" use "not" and "=="  
b. Print true if either the second or third index values for sales is greater than the first index value for sales  
c. Print true if only the second or only the third index value for sales is greater than the first index value for sales  
d. Print true if both the second and third index values for sales is greater than the first index value for sales 

In [318]:
print(not acme_multiple_financials['sales'][0] == acme_multiple_financials['expenses'][0])
print(acme_multiple_financials['sales'][0] < acme_multiple_financials['sales'][1] or acme_multiple_financials['sales'][0] < acme_multiple_financials['sales'][2])
print((acme_multiple_financials['sales'][0] < acme_multiple_financials['sales'][1]) ^ (acme_multiple_financials['sales'][0] < acme_multiple_financials['sales'][2]))
print(acme_multiple_financials['sales'][0] < acme_multiple_financials['sales'][1] and acme_multiple_financials['sales'][0] < acme_multiple_financials['sales'][2])

True
True
True
False


__Short-Circuit Evaluation__  
Short-circuit evaluation means that the logical comparisons are evaluated in order from left to right. As soon as one logical comparison is found that allows for a conclusion, then no additional conditional expressions are evaluated.  For _and_, starting from the left, if a conditional expression returns False, then no additional comparisons are done and the value of the value of the first false is returned (which typically is simply False).  For _or_, starting from the left, if a conditional expression returns True then no additional comparisons are done and the first True value is returned (which typically is True).  
  
There are some common idiomatic patterns that exploit short-circuit evaluation for conciseness of expression.  These expression are very difficult to understand unless you are aware of them (I am not a fan of them because they make the code less readable, but many people still use them so they are good to at least be aware of).  Two common patterns are for handling zero division and for assigning default values.  
  
_Zero Division_  
Suppose you have defined two variables sales_1 and sales_2, and you want to know whether (sales_1 / sales_2) > 0.  This evaluation can be implemented using a simple comparison operator.  However, if sales_2 Python will return an error indicating the zero division is not possible.  It is possible to avoid the zero division using short circuit evaluation as follows: sales_2 and (sales_1 / sales_2) > 0.  To see how this works first create sales_1 and sales_2 and assign these variables the values 100 and 0, respectively.  Then attempt the (sales_1 / sales_2) > 0 comparison.  

In [319]:
sales_1 = 100
sales_2 = 0
print((sales_1 / sales_2) > 0)

ZeroDivisionError: division by zero

Now instead perform the comparison using sales_2 and (sales_1 / sales_2) > 0 and notice how 0 is returned.  The reason for this is that short circuit evaluation compares from left to right and stops comparing if a conditional expression returns False and since sales_2 contains the value 0, which is interpreted as False in a boolean context, short circuit evaluation will stop the evaluation after the first logical comparison and return the value of the first comparison.

In [ ]:
print(sales_2 and (sales_1 / sales_2) > 0)
print(bool(sales_2))

If on the other hand sales_2 is equal to 200 (and sales_1 is still equal to 100), sales_2 is no longer False and the comparison of (sales_1 / sales_2) > 0 is performed.

In [ ]:
sales_2 = 200
print(sales_2 and (sales_1 / sales_2) > 0)

__Exercises 3.4__  
a. Create four variables: sales, prior_sales, number_of_employees, and prior_number_of_employees and assign these variables the values 120, 90, 500, and 490, respectively.  Then create a new variable called abnormal_sales_growth calculated as ((sales - prior_sales) / prior_sales) / ((number_of_employees - prior_number_of_employees) / prior_number_of_employees). What is the value abnormal_sales_growth?  
b. Now assign sales, prior_sales, number_of_employees, and prior_number_of_employees the values 120, 90, 500, and 500, respectively.  What is the value abnormal_sales_growth now?  
c. Use short-circuit evaluation to assign zero to abnormal_sales_growth if number_of_employees – prior_number_of_employees is equal to zero.

In [ ]:
#a.
sales = 120
prior_sales = 90
number_of_employees = 500
prior_number_of_employees = 490
abnormal_sales_growth = ((sales - prior_sales) / prior_sales) / ((number_of_employees - prior_number_of_employees) / prior_number_of_employees)
print(abnormal_sales_growth)

#b.
sales = 120
prior_sales = 90
number_of_employees = 500
prior_number_of_employees = 500
#abnormal_sales_growth = ((sales - prior_sales) / prior_sales) / ((number_of_employees - prior_number_of_employees) / prior_number_of_employees)
print(abnormal_sales_growth)

#c.
abnormal_sales_growth = (number_of_employees - prior_number_of_employees) and ((sales - prior_sales) / prior_sales) / ((number_of_employees - prior_number_of_employees) / prior_number_of_employees)
print(abnormal_sales_growth)

_Selecting a Default Value_  
Another idiom involves selecting a default value when a specified value is zero or empty. For example, suppose you want to assign a variable s to the value contained in another variable called t. But if t is empty, you want to supply a default value.  This is often done using short-circuit evaluation:  
s = t or 'default_value'

This works because if t is non-empty then t is considered True and the evaluation stops and the value of t is returned (recall that when using OR, Python stops evaluating when the first True is encountered and the value of the first True statement is returned). If t is empty, then t is considered False and the evaluation moves over to the default value (which is a non-empty string) that is evaluated as True and therefore returned.

__Exercise 3.5__  
Use the patterns in _Zero Division_ and _Selecting a Default Value_ to assign None to abnormal_sales_growth if number_of_employees – prior_number_of_employees is equal to zero and otherwise the values as calculated by the formula given earlier.  Print the results and then change prior_number_of_employees back to 490 and then rerun the zero division/selecting a default value again (and print the results)

In [ ]:
abnormal_sales_growth = ((number_of_employees - prior_number_of_employees) and ((sales - prior_sales) / prior_sales) / ((number_of_employees - prior_number_of_employees) / prior_number_of_employees)) or None
print(abnormal_sales_growth)
prior_number_of_employees = 490
abnormal_sales_growth = ((number_of_employees - prior_number_of_employees) and ((sales - prior_sales) / prior_sales) / ((number_of_employees - prior_number_of_employees) / prior_number_of_employees)) or None
print(abnormal_sales_growth)

---  
### Control Flow  
The statements in your code are executed in the order that they appear (from top to bottom), but control flow statements can be used to change this top to bottom execution by executing particular statements based on conditional statements and loops.  Conditional statements are implemented in Python using if, elif, else statements and loops are implemented using for loops (while loops are also supported, but they are uncommon in Python data analytics).  Generally, when using Python for data analytics tasks, it is better to avoid if, elif, else and for loops and instead perform the needed work using functions and methods provided in various libraries.  Not only does this allow us to avoid reinventing the wheel, the code provided by well established libraries also performs better in terms of execution time (this code is created in C and other lower level languages, which are faster, rather than Python and has been optimized). This is a major reason why NumPy and Pandas are so important (we will cover NumPy and Pandas in the next two tutorials). There are, however, times when there are no suitable functions in established libraries to help you and then you need to create your own code.  Further, other developers often create code that uses control flow statements and to understand their code it is important to understand these statements.   

#### if, elif, else  
The general structure of if, elif, else is:  
if comparison_1:  
&nbsp; &nbsp; &nbsp; statement_1.a  
&nbsp; &nbsp; &nbsp; statement_1.b  
&nbsp; &nbsp; &nbsp; ...  
elif comparison_2:  
&nbsp; &nbsp; &nbsp; statement_2.a  
&nbsp; &nbsp; &nbsp; statement_2.b  
&nbsp; &nbsp; &nbsp; ...  
else:  
&nbsp; &nbsp; &nbsp; statement_n.a  
&nbsp; &nbsp; &nbsp; statement_n.b  
&nbsp; &nbsp; &nbsp; ...  
There can be zero or more elif parts and the else part is optional (the keyword elif is short of else if).  When a comparison is true the indented statements (the indentions are important) below the comparison (after the colon) are executed. However, only one block among the several if...elif...else blocks is executed. So if comparison_1 and comparison_2 are both True then only the block with Statement_1.xs is executed.  The else block is executed if all other if and elif comparisons return False.

__Exercise 4.1__  
Create two variables, course_percent and letter_grade. Assign the value 88 to course_percent.  Then create an if statement that assigns a value to letter_grade based on the value of course_percent as follows: A if course_percent > 93, A- if course_percent > 90, B+ if course_percent > 87, B if course_percent > 83... , D- if course_percent > 60, and otherwise F.

In [ ]:
course_percent = 88
if course_percent >= 93:
    letter_grade = 'A'
elif course_percent >= 90:
    letter_grade = 'A-'
elif course_percent >= 87:
    letter_grade = 'B+'
elif course_percent >= 83:
    letter_grade = 'B'
elif course_percent >= 80:
    letter_grade = 'B-'
elif course_percent >= 77:
    letter_grade = 'C+'
elif course_percent >= 73:
    letter_grade = 'C'
elif course_percent >= 70:
    letter_grade = 'C-'
elif course_percent >= 67:
    letter_grade = 'D+'
elif course_percent >= 63:
    letter_grade = 'D'
elif course_percent >= 60:
    letter_grade = 'D-'
else:
    letter_grade = 'F'
  
print(letter_grade)

#### For Loops
Loops are used to repeat tasks (the same code is executed zero to many times depending on the loop condition). Python for loops are designed specifically iterate over some type of iterable – typically lists or strings.  For example, a for loop can be used to do something with each element in a list, i.e., we loop over each element in an existing list.  In the most basic form, the for loop will access the value of each element in a list:
  
__Looping over Lists - Element Values__  
for v in list_example:  
&nbsp; &nbsp; &nbsp; print(v)  
  
In this example, v takes on the values of each element in the list_example list.  The print statement is then executed in each iteration (multiple lines of code that are all indented can also be used).  
  
__Looping over Lists - Index and Element Values__    
It is also possible to get the index (and the value) of each element by using enumerate:  
for i, v in enumerate(list_example):  
&nbsp; &nbsp; &nbsp; print(i, v)

When using enumerate, i contains the index and v contains the value of each element.

__Looping a Specific Number of Times__  
Alternatively, an iterable can be created with x number of elements to then have the loop repeated x number of times (as the loop iterates over the iterable). The range command is typically used for this, e.g.,:  
for v in range (1000):  
&nbsp; &nbsp; &nbsp; print(v)  
    
Range creates an iterable object (think list) that goes from 0 to 999.  The loop then iterates over all the elements in the range object with i taking on all the values of each element in the range.  A start value can also be given, i.e., range(start, stop) as can a step value, i.e., range(start, stop, step).  It is, however, not possible to only pass the stop and step parameter values to the range function. 

__Looping over a Dictionary__  
A simple for loop, i.e., for k in dictionary_example, will loop over the keys in the dictionary, i.e., k will contain keys.  To also access the values, the following syntax is used:  
for k, v in dictionary_example.items():  
&nbsp; &nbsp; &nbsp;print('key:', k, 'and value: ', v)
  
__Exercise 4.2__  
a. Create a loop that prints the values of all the elements in list_example.  
b. Create a loop that doubles and prints all values that are integers, only print these integer values. Use the isinstance(object, type) function (which returns True if object is of specified type.    
c. Create a loop that prints the index numbers and the values of all the elements in list_example, e.g., 0: 10 for the first element.  
d. Create a loop that prints the index numbers and the values of all the elements in list_example with the value 10000.  
e. Create a loop that prints the numbers 1 through 20.  
f. Create a loop that prints the number 1 through 19 and only prints uneven numbers.

In [ ]:
#4.2.a
for i in list_example:  
    print(i)

In [ ]:
#4.2.b
for i in list_example:  
    if isinstance(i, int):
        print(i*2)

In [ ]:
#4.2.c
for i, v in enumerate(list_example):  
  print(str(i) + ": " + str(v))

In [ ]:
#4.2.d
for i, v in enumerate(list_example):  
  if v == 10000:
    print(str(i) + ": " + str(v))

In [ ]:
#4.2.e
for i in range (1,21):  
    print(i)

In [ ]:
#4.2.f
for i in range (1,20,2):  
    print(i)

__List Comprehension__  
  
_Overview_:
- Combines for loops (over lists) and if statements.
- Performance is better than using for loops (see additional noted below)
- Generally considered better syntax – but I think they can at times be more difficult to understand (reading list comprehension from right to left makes them easier to understand)
- Returns a list (but needs to be enclosed in square brackets)

_General Syntax_:  
- List comprehension with one if statement (the output expression and the if part are optional):  
[output expression for_loop if condition]  
  
  
- List comprehension with if-else statements (the if statement is before the loop and requires an else and output_1 is before the condition while output_2 is after the else):  
[output_1 if condition_1 else output_2 for_loop]  
  
  
- List comprehension with nested if statement (elif is created by embedding an if statement within the else part of the first if statement):  
[output_1 if condition_1 else output_2 if condition_2 else output_3 for_loop]  
  
Performance Considerations When Working with Sequences  
1. For best performance, use functions from Pandas or NumPy when possible
2. If you must loop, use list comprehension (and list comprehension is generallypreferred over apply() and similar methods like map combined with lambda functions)
3. Only use loops when list comprehension becomes too difficult to understand
  
__Exercise 4.3__   
a. Rewrite 4.2.a as a list comprehension.  
b. Rewrite 4.2.b as a list comprehension.  
c. Double and return all integer values, return other values without modifying them.

In [ ]:
#4.3.a
print([i for i in list_example])

In [325]:
#4.3.b

print([i*2 for i in list_example if isinstance(i, int)])

[20, 200, 20000, 20000]


In [321]:
#4.3.c

print([i*2 if isinstance(i, int) else i for i in list_example])

[20, 200, 20000, 'large', 'very_large', 'the largest', [101, 102], 20000]


---  
### Functions, Standard Libraries, and Packages and Modules

#### Functions  
_Definition_
- reusable piece of code, 
- created to solve a specific problem, 
- two types: (1) built-in functions, e.g., print(), range(), min(), max(), etc., and (2) user defined functions

_syntax_  
def function_name(arguments):  
&nbsp; indented_statement_1  
&nbsp; indented_statement_2  
&nbsp; ……  
&nbsp; ……  
&nbsp; return statement  
  
_arguments (see code below for example)_
- can be optional (arguments with default values in the function definition) or required (arguments with no default values), e.g., **def add_numbers(number_1, number_2=10)**.  For optional arguments:
  - if a value is specified when calling the function then the specified value will be used and otherwise the default value will be used. For example, if the function add_numbers is called using **add_numbers(3)** then the value 3 is assigned to number_1 and number_2 uses the default_value (i.e., 10).  If this function is instead called using **add_numbers(3,5)** then in addition to assigning the value 3 to number_1, 10 is assigned to number_2. 
  - any number of arguments in a function can have a default value, but once a function has a default argument, all the arguments to the right must also have default values, i.e., the following would generate an error: **def add_numbers(number_2=10, number_1):**
   
- positional and keyword arguments
  - when a function is called, arguments can be assigned values in the order that the argument is defined or by keyword, e.g., **add_numbers(3,number_2=20)**
  - keyword arguments must be positioned after positional arguments, i.e., the following would generate an error: **add_numbers(number_1=3,10)**
  
- \* and \*\* arguments (often written as \*args and \*\*kwargs) allows passing in multiple arguments.  When a function is called and values passed to a \*argument, the values are typed one by one separated by a comma and then used as a tuple inside the function.  When a function is called and keys and values are passed to a \** argument, each key and corresponding value are associated using an equal sign and each key-value pair is separated by a comma and then used as a dictionary inside the function.  While these variables are typically named args and kwargs, respectively, any name can be used.  For example **def calculate_numbers(number_1, number_2=10, \*numbers_3_to_n, \*\*numbers_with_keys)**.  This function could then be called using calculate_numbers(3, 20, 10, 20, 7, minus=5, multiply=3), which would result in numbers_3_to_n = (10, 20, 7) and numbers_with_keys = {'minus': 10, 'multiply': 3}. 

In [ ]:
def add_numbers(number_1, number_2 = 10):
    return(number_1 + number_2)

print(add_numbers(1))
print(add_numbers(1, 5))
print(add_numbers(3, number_2 = 20))

def calculate_numbers(number_1, number_2 = 10, *numbers_3_to_n, **numbers_with_keys):
    print(numbers_3_to_n)
    print(numbers_with_keys)
    total = number_1 + number_2
    for tuple_number in numbers_3_to_n:
        total += tuple_number
    
    for operation, dictionary_number in numbers_with_keys.items():  
        if operation == 'minus':
            total -= dictionary_number
        elif operation == 'multiply':     # additional elif would be needed if other types of operations could be performed
            total *= dictionary_number
    return total
calculate_numbers(3, 20, 10, 20, 7, minus = 10, multiply = 3)

__Exercises 5.1__  
a. Use the code in exercise 4.1 and create a function that returns the grade of a student given a specific course percentage.  
b. Create a list, course_scores, and populate the list with multiple scores, e.g., 86, 94, 80.  Use list comprehension to loop through each element in course_scores and convert each element to a course grade using the function created in 5.1.a.  
c. Create a function that can take multiple student scores and returns the grade for all the scores.  
d. Create a function that can take multiple student names and student scores and returns the grade for all the scores.

In [322]:
# 5.1.a
def course_grade(course_percent):
    if course_percent >= 93:
        letter_grade = 'A'
    elif course_percent >= 90:
        letter_grade = 'A-'
    elif course_percent >= 87:
        letter_grade = 'B+'
    elif course_percent >= 83:
        letter_grade = 'B'
    elif course_percent >= 80:
        letter_grade = 'B-'
    elif course_percent >= 77:
        letter_grade = 'C+'
    elif course_percent >= 73:
        letter_grade = 'C'
    elif course_percent >= 70:
        letter_grade = 'C-'
    elif course_percent >= 67:
        letter_grade = 'D+'
    elif course_percent >= 63:
        letter_grade = 'D'
    elif course_percent >= 60:
        letter_grade = 'D-'
    else:
        letter_grade = 'F'
    return letter_grade

print(course_grade(80))
print(course_grade(94))
print(course_grade(86))

B-
A
B


In [324]:
# 5.1.b
course_scores = [86, 94, 80]
print([course_grade(score) for score in course_scores])


['B', 'A', 'B-']


In [ ]:
# 5.1.c
def course_grade(*course_percentages):
    letter_grade_list=[]
    for course_percent in course_percentages:
        if course_percent >= 93:
            letter_grade = 'A'
        elif course_percent >= 90:
            letter_grade = 'A-'
        elif course_percent >= 87:
            letter_grade = 'B+'
        elif course_percent >= 83:
            letter_grade = 'B'
        elif course_percent >= 80:
            letter_grade = 'B-'
        elif course_percent >= 77:
            letter_grade = 'C+'
        elif course_percent >= 73:
            letter_grade = 'C'
        elif course_percent >= 70:
            letter_grade = 'C-'
        elif course_percent >= 67:
            letter_grade = 'D+'
        elif course_percent >= 63:
            letter_grade = 'D'
        elif course_percent >= 60:
            letter_grade = 'D-'
        else:
            letter_grade = 'F'
        letter_grade_list.append(letter_grade)
    return letter_grade_list

print(course_grade(80, 94, 86))

In [ ]:
# 5.1.d
def course_grade(**student_course_percentages):
    letter_grade_dictionary={}
    for name, course_percent in student_course_percentages.items():
        if course_percent >= 93:
            letter_grade = 'A'
        elif course_percent >= 90:
            letter_grade = 'A-'
        elif course_percent >= 87:
            letter_grade = 'B+'
        elif course_percent >= 83:
            letter_grade = 'B'
        elif course_percent >= 80:
            letter_grade = 'B-'
        elif course_percent >= 77:
            letter_grade = 'C+'
        elif course_percent >= 73:
            letter_grade = 'C'
        elif course_percent >= 70:
            letter_grade = 'C-'
        elif course_percent >= 67:
            letter_grade = 'D+'
        elif course_percent >= 63:
            letter_grade = 'D'
        elif course_percent >= 60:
            letter_grade = 'D-'
        else:
            letter_grade = 'F'
        letter_grade_dictionary[name] = letter_grade
    return letter_grade_dictionary

print(course_grade(Johan = 80, John = 94, Johannes = 86))


##### Lambda Functions  
Lambda functions are anonymous functions, i.e. functions without names, that are used where they are created (and typically only there). It is possible to assign a lambda function to a variable, which can then be used in subsequent code.  

_General Syntax_  
lambda argument_list: expression  
  
Argument_list is a comma separated list of arguments (arguments follow the same rules as regular expressions) and expression is an expression that uses these arguments. For example, _lambda x, y: x+y_ takes two arguments and then adds the two arguments together (which is returned by the function).  
  
To apply the function to an argument(s) you either (i) surround the function and the argument(s) with parentheses or (ii) you assign the function to a variable and then use the function like you would a regular function:  
i)  
(lambda x, y: x+y)(3,7)  
  
ii)   
simple_addition = lambda x, y: x+y  
simple_addition(3,7)  


Lambda functions are typically used together with map() and filter() (and sometimes also the reduce function) to apply the lambda function to all elements in a sequence.  The Pandas function .apply() also works similarly to map().  While it is possible and preferable to use list comprehension instead of lambda expressions when applying operations to each element in a sequence (and when possible, even better to use NumPy and Pandas functions), you will see lambda functions used fairly frequently in practice. 

_map(function, iterable)_  
The map() function applies the _function_ to every element in _iterable_ (typically a sequence) and returns an iterator that can be converted to a list using list().

_filter(function, iterable)_  
The filter() function returns each element in _iterable_ for which the _function_ returns true.

__Exercises 5.2__  
a. Create a lambda function that doubles integer values and leave all other values unmodified. Assign the lambda function to a variable named converter.  Test the function using 10 and then 'large' as argument values.
b. Use map() to apply the converter function from 5.2.a on each element in list_example.  
c. Use list comprehension instead of map() to use the converter function on each element in list_example.  
d. Use filter() and a lambda function to create a list of all integer elements (and only these elements) in list_example.  
e. Use list comprehension instead of filter() to create a list of all integer elements (and only these elements) in list_example.

In [ ]:
# 5.2.a
converter = lambda x: x*2 if isinstance(x, int) else x
print(converter(10))
print(converter('large'))

# 5.2.b
print(list(map(converter, list_example)))

# 5.2.c
print([converter(i) for i in list_example])

# 5.2.d
print(list(filter(lambda x: isinstance(x, int), list_example)))

# 5.2.e
print([i for i in list_example if isinstance(i, int)])

#### Standard Libraries  
- Included in Python, but they do not do it all – packages are imported for functionality not provided by the standard library
- Standard library functions: print(), min(), max(), etc.
- Standard constants: False, True, None, etc.
- Standard data types: int, float, bool, str
- Standard file formats (that Python supports reading and writing): csv, excel, etc.

#### Modules and Packages
Packages are folders that contain one or more modules.  Modules are separate .py files that each contain one or more functions.
  
To use a non-standard function, the package that contains the function has to be imported.  It is possible to import the entire package, a specific module within a package, and even a specific function within a specific module. It is also possible to specify an alias (or the full name) to use when referencing the imported package/module/function.  There are two ways to import packages, import... as... and from... import... as... (see below for examples).  When using import... as..., each item except the last has to be a package and the last item can be either a package or module (but not a function).  When using from... import... as... the last item can be a package, module, or function.  The former is typically used to import entire packages and the latter is typically used to import specific functions.

##### Importing Package (and using a function)
Code to import:  
import package_name as package_alias  
  
Code to use function:  
package_alias.module_name.function_name  
  
##### Importing Specific Module (and using a function)
Code to import:  
import package_name.module_name as module_alias  
  
Code to use function:  
module_alias.function_name  
  
##### Importing Specific Function (and using a function)
Code to import:  
from package_name.module_name import function_name as function_alias
  
Code to use function:  
function_alias

__Conventions__   
To increase code readability, aliases are typically only used when it is customary to do so, e.g., when searching for help you will notice things like NumPy being referenced as np, Pandas as pd, StatsModels as sm, etc.  These aliases are fine because of how commonly they are used, but when a specific alias is not commonly used then using the alias can make it difficult to understand the code.  Similarly, it is generally recommended that packages are imported (or packages and modules) rather than specific functions and that dot notation is subsequently used in the code to reference a specific function. If a single function is imported (and dot notation is not used in the code), it can be difficult to know which package the function belongs to (and if this is unclear then it becomes more difficult to understand the code and to search for help about the function).  However, dot notation can also get very long which can also decrease code readability and increase the time it takes to write the code and the risk for typos.  How far to go with dot notation depends on what is customary for the specific package/module/function.  When I am unsure what is customary, I generally import packages/modules so that when I call a function I show one level above the function (which typically is the package) and I only occasionally use aliases.